<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Version.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>RcloneTransferManager</AssemblyName>
    <RootNamespace>RcloneTransferManager</RootNamespace>
    <Authors>Arkie'z K. Khositkhanawut</Authors>
    <Company>Arkie'z K. Khositkhanawut</Company>
    <Product>Rclone Transfer Manager</Product>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\RcloneTransferManager.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System"/>
    <Using Include="System.Collections.Generic"/>
    <Using Include="System.IO"/>
    <Using Include="System.Linq"/>
    <Using Include="System.Threading"/>
    <Using Include="System.Threading.Tasks"/>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\rclone.exe" Link="_internal\rclone.exe" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" ExcludeFromSingleFile="true" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\RcloneTransferManager.ico" />
    <None Update="Assets\RcloneTransferManager.svg" />
  </ItemGroup>
</Project>
